name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install buildozer and dependencies
        run: |
          pip install --upgrade pip setuptools virtualenv
          pip install "cython<3.0.0" buildozer
          sudo apt install -y openjdk-17-jdk \
            build-essential libssl-dev libffi-dev zlib1g-dev autoconf automake libtool
      - name: Accept Android SDK Licenses Manually
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          yes | (yes || true) | buildozer android p4a -- get-licenses || true
      - name: Build APK
        run: buildozer android debug
      - uses: actions/upload-artifact@v4
        with:
          name: led-panel-apk
          path: bin/*.apk
